//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDangKyDichVu
    {
        public int Id { get; set; }
        public int MaDangKy { get; set; }
        public int MaHocSinh { get; set; }
    
        public virtual DangKyDichVu DangKyDichVu { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
