//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu_Lop
    {
        public int Id { get; set; }
        public int MaDichVu { get; set; }
        public int MaLop { get; set; }
    
        public virtual DichVu DichVu { get; set; }
    }
}
